server:
  port: 1337
spring:
  servlet:
    multipart:
      enabled: true
      location: classpath:/public
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/randomchan
    username: postgres
    password: postgres
  flyway:
    locations: classpath:db/migration
  security:
    user:
      name: admin
      password: password
  thymeleaf:
    cache: false
